#!/bin/sh

help() {
  echo "Usage: $0 <revision> <version> [lastrelease]"
  echo
  echo "  <revision>    The revision which should be used for release."
  echo "  <version>     The version of the release."
  echo "  [lastrelease] The revision of the most recent release made."
  echo "                By default it uses the most recent release-tag."
  exit 1
}

MESON_SETUP_ARGS="--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib/openbox --localstatedir=/var"
MESON_SETUP_ARGS="$MESON_SETUP_ARGS --bindir=/usr/bin --libdir=/usr/lib --datadir=/usr/share"

build_and_test() {
  style=$1
  shift
  builddir="$TESTDIR/$style"
  echo "Checking build configuration: $style"
  rm -rf "$builddir"
  meson setup "$builddir" $MESON_SETUP_ARGS "$@" >/dev/null || \
    error "meson setup failed ($style)"
  meson compile -C "$builddir" >/dev/null || \
    error "meson compile failed ($style)"
  meson test -C "$builddir" >/dev/null || \
    error "meson test failed ($style)"
  rm -rf "$builddir"
}

make_dist() {
  distdir="$TESTDIR/dist"
  rm -rf "$distdir"
  meson setup "$distdir" $MESON_SETUP_ARGS >/dev/null || \
    error "meson setup failed (dist)"
  meson dist -C "$distdir" --formats gztar >/dev/null || \
    error "meson dist failed"
  TAR="$distdir/meson-dist/openbox-$VERSION.tar.gz"
  test -e "$TAR" || error "meson dist did not create expected tarball"
  cp "$TAR" "$SRCDIR/" || error "failed to copy tarball to source tree"
  TAR="$SRCDIR/openbox-$VERSION.tar.gz"
}

REV="$1"
test -z "$REV" && help
VERSION="$2"
test -z "$VERSION" && help
LAST="$3"

. release/common

#### CONFIRM SHORTLOG #####

echo Shortlog from previous release:
echo "$SHORTLOG"
echo
echo Shortlog from $LAST contains $(echo "$SHORTLOG"|wc -l) lines
echo -n "ok? (y/n) "
read a
test "$a" = "y" || error "aborted"

#### TEST english po VERSIONS ####

BAD_PO="$(grep Project-Id-Version po/en*.po|grep -v "openbox $VERSION\\\\n")"
test -z "$BAD_PO" || error "wrong version in po files" "$BAD_PO"

#### RESET THE REPO TO A CLEAN STATE ####

git clean -f -x -d -q

#### TEST ALL OPTIONAL COMPILATION FLAGS ####

CFLAGS="-Werror -isystem /usr/lib/glib-2.0" \
  build_and_test "debug" -Dbuildtype=debug

build_and_test "all-options"
build_and_test "no-startup-notification" -Dstartup_notification=disabled
build_and_test "no-xcursor" -Dxcursor=disabled
build_and_test "no-imlib2" -Dimlib2=disabled
build_and_test "no-librsvg" -Dlibrsvg=disabled
build_and_test "no-session" -Dsession_management=disabled
build_and_test "no-xkb" -Dxkb=disabled
build_and_test "no-xrandr" -Dxrandr=disabled
build_and_test "no-xinerama" -Dxinerama=disabled
build_and_test "no-xsync" -Dxsync=disabled

echo Creating release tarball
make_dist

# VERIFY TARBALL

ASC="$SRCDIR/openbox-$VERSION.tar.gz.asc"

test -e "$TAR" || error "release tarball missing"

echo Signing the release tarball:
gpg --sign --detach-sign --armor --output "$ASC" "$TAR" || \
  error "Failed to sign release tarball"

echo Tagging the release:
git tag -s -m "tagging the $VERSION release" "release-$VERSION" $REV || \
  error "Failed to tag the release"

echo "=$VERSION="
echo "$CLNOWRAP"
echo
echo
echo Edit download page:
echo "  http://openbox.org/oldwiki/index.php?title=Openbox:Download&action=edit&section=1"
echo
echo Edit changelog:
echo "  http://openbox.org/oldwiki/index.php?title=Openbox:Changelog&action=edit&section=1"
echo
echo Add the version to the bug tracker:
echo "  https://bugzilla.icculus.org/editversions.cgi?action=add&product=Openbox"
echo
echo Push the tag:
echo "  git push origin tag release-$VERSION"
echo
echo Email:
echo "  ./release/email $*"
echo
echo Update IRC topic and have a beer/juice!
echo
cd "$SRCDIR"
ls -l "$TAR" "$ASC"

clean
exit 0
